name: Purple AI Updater 
on: 
   workflow_dispatch:
   schedule:
     - cron: '0 0 * * *'    # 8 AM GMT+8
     - cron: '0 8 * * *'    # 4 PM GMT+8
     - cron: '0 16 * * *'   # 12 AM GMT+8 (next day locally)

permissions:
  models: read
  
jobs: 
  purpleAIUpdater: 
    runs-on: ubuntu-latest
    environment: prod
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3 
        with: 
          node-version: 16 
      - run: env
      - name: Install dependencies
        run: npm ci 
      - name: Configure github credentials 
        run: |
          git config --local user.name "${GITHUB_ACTOR}"
          git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: Run Purple AI Updater script 
        env:
          SCOPE: ${{ secrets.SCOPE }}
          GOOGLE_CLIENT_EMAIL: ${{ secrets.GOOGLE_CLIENT_EMAIL }}
          GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
        run: |
          node updater/purpleAIUpdater.js 
      - name: Upload Artifact 
        uses: actions/upload-artifact@v4
        with: 
          name: errors.txt 
          path: errors.txt 
